- name: Install virtualenv module
  apt:
    name: python-virtualenv
    update_cache: yes

- name: Install docker-py in venv
  pip: 
    name: docker-py
    virtualenv: /tmp/venv
    virtualenv_python: python2.7
    virtualenv_command: virtualenv

- name: Set docker-py python env
  set_fact:
    ansible_python_interpreter: "/tmp/venv/bin/python"

    
- name: Deploy python-listener app in docker container
  docker_container:
    name: python-listener
    image: python-listener
    ports: "8080:8080"

